# Generated by Django 6.0.4 on 2026-04-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('inicio', 'Inicio'), ('dsf', 'Desarrollo de Software'), ('adb', 'Administración de Bases de Datos'), ('gr', 'Gestión de Redes'), ('ia', 'Inteligencia Artificial')], default='inicio', max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('url', models.CharField(blank=True, default='#', max_length=200)),
                ('icono', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
